### ISSUE TITLE
Env variables not parsing

### ISSUE THREAD

**Issue by flythenimbus** [dugajean/goke#31]
When using an env var from `global.env` and `{task}.env` in task, they should be substituted with the respective value. Currently it results in an empty string.

For example:

```
greet-cats:
  run:
    - 'echo "Hello ${CAT}"'
  env:
    CAT: "Kitty"
```

Outputs `Hello `. Same goes for this:

```
global:
  env:
    CAT: "Kitty"

greet-cats:
  run:
    - 'echo "Hello ${CAT}"'
 ```

**Expected behaviour:**

The output should be `Hello Kitty`.
